server:
  port: 8887
  
spring:
  application:
    name: customer-service  h2:    console:      enabled: true
      
eureka:  client:    service-url:
      default-zone: http://localhost:8761/eureka