server:
  port: 8765

spring:
  application:
    name: Zuul
info:
  description: Exploring Zuul proxy servers
  
#must also register Zuul with eureka 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true